import type { BeforeAfterTrackInfo } from '@/types/BeforeAfterTrackInfo';

export const beforeAftertracks: BeforeAfterTrackInfo[] = [
  {
    name: 'Soul R&B',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Blue Rock',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Funky Groove',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Funky Groove',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Modern Jazz',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Indie Pop',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Dream Pop',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Dream Pop',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Funky Groove',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Soul R&B',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
  {
    name: 'Soul R&B',
    after_path:"mp3/beforeAfterTrack/soul-test/after/soul_after.mp3",
    before_path: 'mp3/beforeAfterTrack/soul-test/before/soul_before.mp3',
    tags: [],
    time: 0,
  },
];